### create category 
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "food"
}

### GET categories
GET http://localhost:3000/categories
Content-Type: application/json
